// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9YJtyxh0mmBSTAlP8AGMfHfWeg4f3fVo',
    appId: '1:381111619833:web:280b2275e9219bae0ed228',
    messagingSenderId: '381111619833',
    projectId: 'sient-guard-kareem',
    authDomain: 'sient-guard-kareem.firebaseapp.com',
    storageBucket: 'sient-guard-kareem.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTXtetkSgli9kViXEHHSVyYxzxFJ6g49k',
    appId: '1:381111619833:android:55c43602c0be9aee0ed228',
    messagingSenderId: '381111619833',
    projectId: 'sient-guard-kareem',
    storageBucket: 'sient-guard-kareem.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQWSuQjeHwsK3yUhiG_NC0kC8l5aF4zNE',
    appId: '1:381111619833:ios:bf01ea7170b4d7c80ed228',
    messagingSenderId: '381111619833',
    projectId: 'sient-guard-kareem',
    storageBucket: 'sient-guard-kareem.firebasestorage.app',
    iosBundleId: 'com.example.silentGuard',
  );
}
